/* Copyright (c) 2025 Perpetuator LLC */
/**
 * M3 Palette Generator
 *
 * This script generates Material Design 3 (MD3) tonal palettes from base hex colors
 * using Google's official HCT (Hue, Chroma, Tone) algorithm.
 *
 * Usage:
 *   yarn theme:generate
 *
 * When to run:
 *   - When changing base brand colors (primary, secondary, tertiary)
 *   - When adding new semantic colors
 *   - NOT needed for routine development
 *
 * The output file (src/styles/_generated-palettes.scss) should be committed to git.
 */

import fs from 'fs';
import path from 'path';
import { argbFromHex, hexFromArgb, TonalPalette, Hct } from '@material/material-color-utilities';

// ============================================================================
// Base Colors - Single source of truth for brand identity
// Change these values and run `yarn theme:generate` to update palettes
// ============================================================================
const BASE_COLORS: Record<string, string> = {
  primary: '#3f97ff', // Capital Blue
  secondary: '#f14a00', // Vibrant Orange
  tertiary: '#8b3aa4', // Rich Purple
  error: '#ba1a1a', // Standard Error Red
  success: '#2e7d32', // Success Green
  warning: '#ed6c02', // Warning Amber/Orange
  info: '#0288d1', // Info Blue
};

// Standard MD3 tones
const STANDARD_TONES = [0, 10, 20, 25, 30, 35, 40, 50, 60, 70, 80, 90, 95, 98, 99, 100];

// Extended tones required for neutral palettes
const NEUTRAL_TONES = [
  0, 4, 6, 10, 12, 17, 20, 22, 24, 25, 30, 35, 40, 50, 60, 70, 80, 87, 90, 92, 94, 95, 96, 98, 99, 100,
];

// ============================================================================
// Palette Generation
// ============================================================================

function generatePalette(hexColor: string, tones: number[]): Record<number, string> {
  const argb = argbFromHex(hexColor);
  const palette = TonalPalette.fromInt(argb);

  const result: Record<number, string> = {};
  tones.forEach((tone) => {
    const color = palette.tone(tone);
    result[tone] = hexFromArgb(color);
  });

  return result;
}

// Generate neutral palette with specific chroma (low saturation)
function generateNeutralPalette(baseHexColor: string, chroma: number, tones: number[]): Record<number, string> {
  const hct = Hct.fromInt(argbFromHex(baseHexColor));
  const hue = hct.hue;

  const result: Record<number, string> = {};
  tones.forEach((tone) => {
    const neutralHct = Hct.from(hue, chroma, tone);
    result[tone] = hexFromArgb(neutralHct.toInt());
  });

  return result;
}

function formatPaletteAsScss(name: string, palette: Record<number, string>): string {
  const entries = Object.entries(palette)
    .map(([tone, hex]) => `    ${tone}: ${hex},`)
    .join('\n');

  return `  ${name}: (\n${entries}\n  ),`;
}

function generateScssFile(): string {
  const timestamp = new Date().toISOString();

  let scss = `/* Copyright (c) 2025 Perpetuator LLC */
// ============================================================================
// Generated Material Design 3 Palettes
// DO NOT EDIT MANUALLY - Generated by scripts/generate-palettes.ts
// Last updated: ${timestamp}
//
// To regenerate: yarn theme:generate
// ============================================================================

@use 'sass:map';

// Base colors used to generate these palettes:
// primary: ${BASE_COLORS.primary}
// secondary: ${BASE_COLORS.secondary}
// tertiary: ${BASE_COLORS.tertiary}
// error: ${BASE_COLORS.error}
// success: ${BASE_COLORS.success}
// warning: ${BASE_COLORS.warning}
// info: ${BASE_COLORS.info}

$palettes: (
`;

  // Generate core palettes with standard tones
  ['primary', 'secondary', 'tertiary', 'error'].forEach((colorName) => {
    const palette = generatePalette(BASE_COLORS[colorName], STANDARD_TONES);
    scss += formatPaletteAsScss(colorName, palette) + '\n';
  });

  // Generate neutral palettes with LOW CHROMA (this is the key!)
  // Neutral: chroma 4 (very desaturated, almost gray)
  // Neutral-variant: chroma 8 (slightly more color, for surfaces)
  const neutralPalette = generateNeutralPalette(BASE_COLORS.primary, 4, NEUTRAL_TONES);
  const neutralVariantPalette = generateNeutralPalette(BASE_COLORS.primary, 8, NEUTRAL_TONES);

  scss += formatPaletteAsScss('neutral', neutralPalette) + '\n';
  scss += formatPaletteAsScss('neutral-variant', neutralVariantPalette) + '\n';

  // Generate extended semantic palettes
  ['success', 'warning', 'info'].forEach((colorName) => {
    const palette = generatePalette(BASE_COLORS[colorName], STANDARD_TONES);
    scss += formatPaletteAsScss(colorName, palette) + '\n';
  });

  scss += `);\n\n`;

  // Export individual palette variables for direct access
  scss += `// ============================================================================
// Individual Palette Variables (for direct access)
// ============================================================================
$primary-palette: map.get($palettes, primary);
$secondary-palette: map.get($palettes, secondary);
$tertiary-palette: map.get($palettes, tertiary);
$neutral-palette: map.get($palettes, neutral);
$neutral-variant-palette: map.get($palettes, neutral-variant);
$error-palette: map.get($palettes, error);
$success-palette: map.get($palettes, success);
$warning-palette: map.get($palettes, warning);
$info-palette: map.get($palettes, info);

`;

  // Add helper functions
  scss += `// ============================================================================
// Helper Functions
// ============================================================================

// Get a specific palette by name
@function get-palette($name) {
  @return map.get($palettes, $name);
}

// Get a specific tone from a palette
@function get-tone($palette-name, $tone) {
  $palette: map.get($palettes, $palette-name);
  @return map.get($palette, $tone);
}
`;

  return scss;
}

// ============================================================================
// Main
// ============================================================================

const outputPath = path.join(process.cwd(), 'src/styles/_generated-palettes.scss');
const scssContent = generateScssFile();

fs.writeFileSync(outputPath, scssContent);

console.log('✅ Generated M3 palettes successfully!');
console.log(`   Output: ${outputPath}`);
console.log('');
console.log('Base colors used:');
Object.entries(BASE_COLORS).forEach(([name, hex]) => {
  console.log(`   ${name}: ${hex}`);
});
