// Copyright (c) 2025-2026 Perpetuator LLC
/**
 * M3 Theme Palette Generator
 *
 * Generates Material Design 3 tonal palettes from base hex colors using
 * Google's HCT algorithm. The output is a generated Sass partial consumed by
 * src/m3-theme.scss, which remains the app's single public theme entrypoint.
 *
 * Usage:
 *   yarn theme:generate
 */

import fs from 'fs';
import path from 'path';
import { argbFromHex, hexFromArgb, TonalPalette, Hct } from '@material/material-color-utilities';

const BASE_COLORS: Record<string, string> = {
  primary: '#3b82f6',
  secondary: '#22d3ee',
  tertiary: '#a78bfa',
  accent: '#f97316',
  error: '#ef4444',
  success: '#10b981',
  warning: '#fbbf24',
  info: '#38bdf8',
};

const MATERIAL_TONES = [0, 10, 20, 25, 30, 35, 40, 50, 60, 70, 80, 90, 95, 98, 99, 100];
const NEUTRAL_TONES = [
  0, 4, 6, 10, 12, 17, 20, 22, 24, 25, 30, 35, 40, 50, 60, 70, 80, 87, 90, 92, 94, 95, 96, 98, 99, 100,
];

function generatePalette(hexColor: string, tones: number[]): Record<number, string> {
  const palette = TonalPalette.fromInt(argbFromHex(hexColor));
  const result: Record<number, string> = {};

  tones.forEach((tone) => {
    result[tone] = hexFromArgb(palette.tone(tone));
  });

  return result;
}

function generateNeutralPalette(baseHexColor: string, chroma: number, tones: number[]): Record<number, string> {
  const hue = Hct.fromInt(argbFromHex(baseHexColor)).hue;
  const result: Record<number, string> = {};

  tones.forEach((tone) => {
    result[tone] = hexFromArgb(Hct.from(hue, chroma, tone).toInt());
  });

  return result;
}

function formatPalette(palette: Record<number, string>): string {
  const entries = Object.entries(palette);
  const lines: string[] = [];

  for (let i = 0; i < entries.length; i += 4) {
    const chunk = entries.slice(i, i + 4);
    lines.push(`    ${chunk.map(([tone, hex]) => `${tone}: ${hex}`).join(', ')},`);
  }

  return lines.join('\n');
}

function formatThemePalettes(): string {
  const palettes: Record<string, Record<number, string>> = {
    primary: generatePalette(BASE_COLORS['primary'], MATERIAL_TONES),
    secondary: generatePalette(BASE_COLORS['secondary'], MATERIAL_TONES),
    tertiary: generatePalette(BASE_COLORS['tertiary'], MATERIAL_TONES),
    accent: generatePalette(BASE_COLORS['accent'], MATERIAL_TONES),
    error: generatePalette(BASE_COLORS['error'], MATERIAL_TONES),
    neutral: generateNeutralPalette(BASE_COLORS['primary'], 4, NEUTRAL_TONES),
    'neutral-variant': generateNeutralPalette(BASE_COLORS['primary'], 8, NEUTRAL_TONES),
    success: generatePalette(BASE_COLORS['success'], MATERIAL_TONES),
    warning: generatePalette(BASE_COLORS['warning'], MATERIAL_TONES),
    info: generatePalette(BASE_COLORS['info'], MATERIAL_TONES),
  };

  return Object.entries(palettes)
    .map(
      ([name, palette]) => `  ${name}: (
${formatPalette(palette)}
  ),`,
    )
    .join('\n');
}

function formatMaterialThemePalettes(): string {
  const palettes: Record<string, Record<number, string>> = {
    primary: generatePalette(BASE_COLORS['primary'], MATERIAL_TONES),
    secondary: generatePalette(BASE_COLORS['secondary'], MATERIAL_TONES),
    tertiary: generatePalette(BASE_COLORS['tertiary'], MATERIAL_TONES),
    error: generatePalette(BASE_COLORS['error'], MATERIAL_TONES),
    neutral: generateNeutralPalette(BASE_COLORS['primary'], 4, MATERIAL_TONES),
    'neutral-variant': generateNeutralPalette(BASE_COLORS['primary'], 8, MATERIAL_TONES),
  };

  return Object.entries(palettes)
    .map(
      ([name, palette]) => `  ${name}: (
${formatPalette(palette)}
  ),`,
    )
    .join('\n');
}

function generateOutput(): string {
  const timestamp = new Date().toISOString();
  const baseColorLines = Object.entries(BASE_COLORS)
    .map(([name, hex]) => `//   ${name}: ${hex}`)
    .join('\n');

  return `/* Copyright (c) 2025-2026 Perpetuator LLC */
// ============================================================================
// Generated M3 Theme Palettes
// DO NOT EDIT - Generated by: yarn theme:generate
// Generated at: ${timestamp}
//
// Base colors:
${baseColorLines}
// ============================================================================

$material-palettes: (
${formatMaterialThemePalettes()}
);

$theme-palettes: (
${formatThemePalettes()}
);
`;
}

const output = generateOutput();
const outputPath = path.join(process.cwd(), 'src/styles/_theme-palettes.generated.scss');

fs.writeFileSync(outputPath, output);

console.log('Generated M3 theme palettes.');
console.log(`Output file: ${outputPath}`);
console.log('');
console.log('Base colors used:');
Object.entries(BASE_COLORS).forEach(([name, hex]) => {
  console.log(`  ${name}: ${hex}`);
});
console.log('');
console.log('src/m3-theme.scss consumes this generated palette partial.');
