/* Copyright (c) 2025 Perpetuator LLC */
/**
 * M3 Palette Generator
 *
 * This script generates Material Design 3 (MD3) tonal palettes from base hex colors
 * using Google's official HCT (Hue, Chroma, Tone) algorithm.
 *
 * Due to Angular Material's SCSS module validation limitations, generated palettes
 * cannot be imported via @use. Instead, this script outputs palette definitions
 * that should be copied into m3-theme.scss.
 *
 * Usage:
 *   yarn theme:generate
 *
 * Then copy the output from src/styles/_generated-palettes.txt into m3-theme.scss
 */

import fs from 'fs';
import path from 'path';
import { argbFromHex, hexFromArgb, TonalPalette, Hct } from '@material/material-color-utilities';

// ============================================================================
// Base Colors - Single source of truth for brand identity
// Change these values and run `yarn theme:generate` to regenerate palettes
// ============================================================================
const BASE_COLORS: Record<string, string> = {
  primary: '#3f97ff', // Capital Blue
  secondary: '#f14a00', // Vibrant Orange
  tertiary: '#8b3aa4', // Rich Purple
  error: '#ba1a1a', // Standard Error Red
  success: '#2e7d32', // Success Green
  warning: '#ed6c02', // Warning Amber/Orange
  info: '#0288d1', // Info Blue
};

// Standard MD3 tones
const STANDARD_TONES = [0, 10, 20, 25, 30, 35, 40, 50, 60, 70, 80, 90, 95, 98, 99, 100];

// Extended tones required for neutral palettes
const NEUTRAL_TONES = [
  0, 4, 6, 10, 12, 17, 20, 22, 24, 25, 30, 35, 40, 50, 60, 70, 80, 87, 90, 92, 94, 95, 96, 98, 99, 100,
];

// ============================================================================
// Palette Generation
// ============================================================================

function generatePalette(hexColor: string, tones: number[]): Record<number, string> {
  const argb = argbFromHex(hexColor);
  const palette = TonalPalette.fromInt(argb);

  const result: Record<number, string> = {};
  tones.forEach((tone) => {
    const color = palette.tone(tone);
    result[tone] = hexFromArgb(color);
  });

  return result;
}

function generateNeutralPalette(baseHexColor: string, chroma: number, tones: number[]): Record<number, string> {
  const hct = Hct.fromInt(argbFromHex(baseHexColor));
  const hue = hct.hue;

  const result: Record<number, string> = {};
  tones.forEach((tone) => {
    const neutralHct = Hct.from(hue, chroma, tone);
    result[tone] = hexFromArgb(neutralHct.toInt());
  });

  return result;
}

function formatPaletteCompact(palette: Record<number, string>): string {
  const entries = Object.entries(palette);
  const lines: string[] = [];

  // Group into lines of ~4 values for readability
  for (let i = 0; i < entries.length; i += 4) {
    const chunk = entries.slice(i, i + 4);
    const line = chunk.map(([tone, hex]) => `${tone}: ${hex}`).join(', ');
    lines.push('    ' + line + ',');
  }

  return lines.join('\n');
}

function generateOutput(): string {
  const timestamp = new Date().toISOString();

  const primaryPalette = generatePalette(BASE_COLORS.primary, STANDARD_TONES);
  const secondaryPalette = generatePalette(BASE_COLORS.secondary, STANDARD_TONES);
  const tertiaryPalette = generatePalette(BASE_COLORS.tertiary, STANDARD_TONES);
  const neutralPalette = generateNeutralPalette(BASE_COLORS.primary, 4, NEUTRAL_TONES);
  const neutralVariantPalette = generateNeutralPalette(BASE_COLORS.primary, 8, NEUTRAL_TONES);

  return `// ============================================================================
// Core Material Palettes (HCT-generated)
// Generated by: yarn theme:generate
// Generated at: ${timestamp}
// Base colors: primary=${BASE_COLORS.primary}, secondary=${BASE_COLORS.secondary}, tertiary=${BASE_COLORS.tertiary}
//
// Copy this entire section into m3-theme.scss, replacing the existing $_palettes
// ============================================================================
$_palettes: (
  primary: (
${formatPaletteCompact(primaryPalette)}
  ),
  secondary: (
${formatPaletteCompact(secondaryPalette)}
  ),
  tertiary: (
${formatPaletteCompact(tertiaryPalette)}
  ),
  neutral: (
${formatPaletteCompact(neutralPalette)}
  ),
  neutral-variant: (
${formatPaletteCompact(neutralVariantPalette)}
  ),
  // Extended semantic palettes - generated from base colors (not validated by Material)
  error: generate-palette($base-error),
  success: generate-palette($base-success),
  warning: generate-palette($base-warning),
  info: generate-palette($base-info),
);
`;
}

// ============================================================================
// Main
// ============================================================================

const output = generateOutput();
const outputPath = path.join(process.cwd(), 'src/styles/_generated-palettes.txt');

fs.writeFileSync(outputPath, output);

console.log('✅ Generated M3 palettes!');
console.log(`   Output file: ${outputPath}`);
console.log('');
console.log('Base colors used:');
Object.entries(BASE_COLORS).forEach(([name, hex]) => {
  console.log(`   ${name}: ${hex}`);
});
console.log('');
console.log('Next steps:');
console.log('   1. Open src/styles/_generated-palettes.txt');
console.log('   2. Copy the $_palettes section');
console.log('   3. Paste into src/m3-theme.scss (replace existing $_palettes)');
console.log('   4. Run: yarn build');
console.log('');
console.log('Generated palette preview:');
console.log('─'.repeat(60));
console.log(output);
