#!/usr/bin/env bash
# Copyright (c) 2024-2026 Perpetuator LLC
#
# Generate a dotenv file (.env.stage by default) from OpenBao secrets for the
# runtime-config Docker image.
#
# Unlike the legacy generate-env-from-vault.sh (which renders a TypeScript file
# that gets baked into the image), this script writes CC_FE_* environment
# variables that docker-compose loads into the container at start time.
#
# Usage:
#   ./scripts/generate-env-from-vault-runtime.sh [vault_path] [output_file]
#
# Defaults:
#   vault_path  = secret/services/cc-fe/staging
#   output_file = .env.stage (in current working directory)
#
# Prerequisites:
#   - vault CLI installed
#   - VAULT_ADDR set (default: https://vault.perpetuator.io)
#   - Authenticated via AppRole files at /etc/vault/ or VAULT_TOKEN env var

set -euo pipefail

VAULT_PATH="${1:-secret/services/cc-fe/staging}"
OUTPUT_FILE="${2:-.env.stage}"
VAULT_ADDR="${VAULT_ADDR:-https://vault.perpetuator.io}"

export VAULT_ADDR

# --- Auth via AppRole if not already authenticated ---
if ! vault token lookup &>/dev/null; then
  ROLE_ID_FILE="${ROLE_ID_FILE:-/etc/vault/vault-role-id}"
  SECRET_ID_FILE="${SECRET_ID_FILE:-/etc/vault/vault-secret-id}"

  if [[ -f "${ROLE_ID_FILE}" && -f "${SECRET_ID_FILE}" ]]; then
    echo "Authenticating to OpenBao via AppRole..."
    VAULT_TOKEN=$(vault write -field=token auth/approle/login \
      role_id="$(cat "${ROLE_ID_FILE}")" \
      secret_id="$(cat "${SECRET_ID_FILE}")")
    export VAULT_TOKEN
  else
    echo "ERROR: Not authenticated and AppRole files not found at:" >&2
    echo "  ${ROLE_ID_FILE}" >&2
    echo "  ${SECRET_ID_FILE}" >&2
    echo "Set VAULT_TOKEN or provide AppRole credential files." >&2
    exit 1
  fi
fi

# --- Fetch secrets from OpenBao ---
echo "Fetching secrets from ${VAULT_PATH}..."
SECRETS_JSON=$(vault kv get -format=json "${VAULT_PATH}" 2>/dev/null) || {
  echo "ERROR: Failed to read secrets from ${VAULT_PATH}" >&2
  echo "Ensure the path exists and the token has read access." >&2
  exit 1
}

# --- Extract values ---
extract() {
  echo "${SECRETS_JSON}" | jq -r ".data.data.${1} // empty"
}

API_URL=$(extract api_url)
SITE_URL=$(extract site_url)
STRIPE_PUBLIC_KEY=$(extract stripe_public_key)
OAUTH_ISSUER=$(extract oauth_issuer)
OAUTH_CLIENT_ID=$(extract oauth_client_id)
OAUTH_SCOPES=$(extract oauth_scopes)

# --- Validate required values ---
MISSING=()
[[ -z "${API_URL}" ]] && MISSING+=(api_url)
[[ -z "${SITE_URL}" ]] && MISSING+=(site_url)
[[ -z "${STRIPE_PUBLIC_KEY}" ]] && MISSING+=(stripe_public_key)
[[ -z "${OAUTH_ISSUER}" ]] && MISSING+=(oauth_issuer)
[[ -z "${OAUTH_CLIENT_ID}" ]] && MISSING+=(oauth_client_id)

if [[ ${#MISSING[@]} -gt 0 ]]; then
  echo "ERROR: Missing required secrets at ${VAULT_PATH}: ${MISSING[*]}" >&2
  exit 1
fi

# Default oauth_scopes if not set
OAUTH_SCOPES="${OAUTH_SCOPES:-read write}"

# --- Write dotenv file ---
# umask ensures the file is created mode 600 (owner read/write only) so
# secrets aren't readable by other users on a shared host.
umask 077
cat > "${OUTPUT_FILE}" <<EOF
# Generated by scripts/generate-env-from-vault-runtime.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')
# Source: OpenBao ${VAULT_PATH}
# DO NOT COMMIT — this file contains runtime secrets.
CC_FE_PRODUCTION=true
CC_FE_API_URL=${API_URL}
CC_FE_SITE_URL=${SITE_URL}
CC_FE_STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
CC_FE_OAUTH_ISSUER=${OAUTH_ISSUER}
CC_FE_OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
CC_FE_OAUTH_SCOPES=${OAUTH_SCOPES}
EOF

echo "Wrote ${OUTPUT_FILE} from OpenBao (${VAULT_PATH})"
echo "  API_URL:      ${API_URL}"
echo "  SITE_URL:     ${SITE_URL}"
echo "  OAUTH_ISSUER: ${OAUTH_ISSUER}"
echo "  STRIPE_KEY:   ${STRIPE_PUBLIC_KEY:0:20}..."
echo "  CLIENT_ID:    ${OAUTH_CLIENT_ID:0:10}..."
